# Generated by Django 3.0.6 on 2020-05-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntrySignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='some string', max_length=122)),
                ('psw', models.CharField(max_length=122)),
                ('fname', models.CharField(max_length=122)),
                ('lname', models.CharField(max_length=122)),
                ('country', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('zipp', models.BigIntegerField(default=0)),
                ('gender', models.CharField(max_length=10)),
                ('interested_in', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=15)),
                ('religion', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=30)),
                ('education_status', models.CharField(max_length=20)),
                ('subject', models.TextField(default=None)),
                ('dob', models.DateField(auto_now_add=True)),
                ('dp', models.FileField(default=None, upload_to='static/dps')),
            ],
        ),
    ]
