# Generated by Django 3.0.6 on 2020-06-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrysignup',
            name='id',
        ),
        migrations.AlterField(
            model_name='entrysignup',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='entrysignup',
            name='dp',
            field=models.ImageField(blank=True, default='img.jpg', null=True, upload_to='media', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='entrysignup',
            name='subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entrysignup',
            name='uname',
            field=models.CharField(max_length=122, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entrysignup',
            name='zipp',
            field=models.IntegerField(),
        ),
    ]
